
###对于 QoS 类为 Guaranteed 的 Pod条件
#1.Pod 中的每个容器，包含初始化容器，必须指定内存请求和内存限制，并且两者要相等。
#2.Pod 中的每个容器，包含初始化容器，必须指定 CPU 请求和 CPU 限制，并且两者要相等。

apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
