apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "tomcat-example-nfs"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: tomcat
    app.kubernetes.io/component: tomcat
    app.kubernetes.io/name: tomcat
  name: tomcat-dynamic-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem