apiVersion: v1
kind: Pod
metadata:
  name: task-nfs-pv-pod
  namespace: demo
spec:
  volumes:
    - name: nfs-pv-storage
      persistentVolumeClaim:
        claimName: nfs-pv-claim
  containers:
    - name: task-nfs-pv-container
      image: nginx:1.14.2
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nfs-pv-storage
